//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prakt_21._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCatalog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductCatalog()
        {
            this.Plans = new HashSet<Plan>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public int Shop { get; set; }
        public int ProductGroup { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plan> Plans { get; set; }
        public virtual ProductGroup ProductGroup1 { get; set; }
        public virtual ShopCatalog ShopCatalog { get; set; }
    }
}
